
name: DeployServer

on:
  workflow_dispatch:
 
jobs:
    build:
        runs-on: ubuntu-latest
 
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22.x" 
            - run: npm install
            - run: npm run build
            - name: TranslateFile
            #  uses: wangyucode/sftp-upload-action@v2.0.4
              uses: cross-the-world/ssh-scp-ssh-pipelines@latest
              with:
                  host: ${{ secrets.SERVER_IP }} #你的nginx服务器公网ip
                  port: ${{ secrets.SERVER_PORT }} #你的nginx服务器ssh端口
                  user: ${{ secrets.USERNAME }} #你的nginx服务器用户名
                  pass: ${{ secrets.PASSWORD }} #你的nginx服务器密码
                  scp: ./dist =>/home/web/ 
               #   remoteDir: ${{ secrets.SERVER_DESTINATION }} #你要把你build好的文件夹放到nginx服务器上的什么位置，一般都是nginx配置的站点路径
